export const siteConfig = {
  url: "https://labib108.vercel.app",
  name: "Sheikh Abu Bakkar Siddiq",
  shortName: "Labib",
  alternateNames: [
    "Sheikh Abu Bakkar Siddiq",
    "Abu Bakkar Siddiq",
    "Abu Bakkar Siddikh Labib",
    "Labib",
    "Labib108",
    "Sheikh Abu Bakkar Siddikh",
  ],
  title: "Sheikh Abu Bakkar Siddiq (Labib) | Backend Engineer | KUET",
  description:
    "Sheikh Abu Bakkar Siddiq (Labib) — Backend Software Engineer from KUET. Building microservices, distributed systems, NestJS, TypeScript, PostgreSQL, and cloud architecture. Portfolio of Nagorik Technologies & professional projects.",
  keywords: [
    "Labib",
    "Labib KUET",
    "Sheikh Abu Bakkar Siddiq",
    "Abu Bakkar Siddiq",
    "Abu Bakkar Siddikh Labib",
    "Labib portfolio",
    "KUET CSE",
    "Khulna University of Engineering & Technology",
    "Backend Engineer Bangladesh",
    "NestJS developer",
    "microservices",
    "distributed systems",
    "TypeScript backend",
    "gRPC",
    "PostgreSQL",
    "Redis",
    "Nagorik Technologies",
    "BAE Innovation",
  ],
  email: "abubuckkersiddikh@gmail.com",
  phone: "+8801720843651",
  sameAs: [
    "https://github.com/labib108",
    "https://www.linkedin.com/in/abu-buckker-siddikh-labib/",
    "https://x.com/Labib_20",
    "https://www.facebook.com/siddikh.labib",
  ],
  jobTitle: "Backend Software Engineer",
  worksFor: "Nagorik Technologies Limited",
  alumniOf: "Khulna University of Engineering & Technology (KUET)",
  image: "/images/labib3.jpeg",
} as const;
